### ISSUE TITLE
CLI App Build Error

### ISSUE THREAD

**Issue by riogrande100** [Qeepsake/react-native-file-utils#24]
Have an app that when running gradlew assembleRelease 

i get the following error. This worked before upgrading to expo sdk 46 and react-native 0.69

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':qeepsake_react-native-file-utils:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.tasks.VerifyLibraryResourcesTask$Action
   > Android resource linking failed
     ERROR:/Users/riogrande100/.gradle/caches/transforms-3/7dad25162e0ba98f9fd2ff8ab8cdde1c/transformed/core-1.7.0/res/values/values.xml:105:5-114:25: AAPT: error: resource android:attr/lStar not found.

any ideas?

**Comment by riogrande100** [comment]
Issue resolved by changing gradlew assembleRelease to app:assesmbleRelease

And bumoing kotlin verison to 1.7.20 in build.grade

```json
buildscript {
    def getMyVersionCode = { ->
        def code = project.hasProperty('versionCode') ? versionCode.toInteger() : 9999
        println "VersionCode is set to $code"
        return code
    }

    def getMyVersionName = { ->
        def name = project.hasProperty('versionName') ? versionName : "2.0.9999"
        println "VersionName is set to $name"
        return name
    }
    
    ext {
        buildToolsVersion = "31.0.0"
        minSdkVersion = 24
        compileSdkVersion = 31
        targetSdkVersion = 31
        entryFile = "src/index.ts"
        versionName = getMyVersionName()
        versionCode = getMyVersionCode()
        kotlinVersion = "1.7.20"

        if (System.properties['os.arch'] == "aarch64") {
            // For M1 Users we need to use the NDK 24 which added support for aarch64
            ndkVersion = "24.0.8215888"
        } else {
            // Otherwise we default to the side-by-side NDK version from AGP.
            ndkVersion = "21.4.7075529"
        }
    }
    repositories {
        google()
        mavenCentral()
        jcenter()
    }
    dependencies {
        classpath("com.android.tools.build:gradle:7.0.4")
        classpath("com.facebook.react:react-native-gradle-plugin") 
        classpath("de.undercouch:gradle-download-task:4.1.2")
        classpath 'com.google.gms:google-services:4.3.10'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.7.20"
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}
```

**Comment by lukebrandonfarrell** [comment]
@riogrande100 Any chance you can make a PR, I can review, and we can release this to others? :)

**Comment by riogrande100** [comment]
@lukebrandonfarrell there was actually no code change, this was done on the main app. And not an edit to [react-native-file-utils](https://github.com/Qeepsake/react-native-file-utils)
